### ISSUE TITLE
feat(files): Support File Uploads

### ISSUE THREAD

**Issue by alfl** [kubelt/web3-publish#19]
# Why

Users might want to upload files/directories instead of DAG content. For example, the PDF output of a TeX build might be what the user wants to publish to a stable name.

# What

Related to Issue #5:

Add support, probably to the action configuration YAML, for file (as opposed to DAG) uploads:

```
      - name: Publish unrevealed packs to web3
        id: unrevealed
        uses: kubelt/web3-publish@v0-pre-alpha
        with:
          as: "file"  #  or "dag"
          secret: ${{ secrets.NAME_PUBLISHING_KEY }}
          glob: "**/unrevealed.json"
          published: false
```

The `as: "file"  # or "dag"` piece allows us to configure which IPFS API is called: `ipfs add` or `ipfs dag import`.

Eventually this will need to extend into descriptors of the data, for example forcing particular file types.
